%% 字体

\setCJKmainfont[BoldFont={Noto Serif CJK SC Bold},ItalicFont={Noto Sans CJK SC}]{Noto Serif CJK SC}
\setCJKsansfont{Noto Sans CJK SC}
\setCJKmonofont{Sarasa Mono SC}
\setCJKfamilyfont{zhsong}{Noto Serif CJK SC}
\setCJKfamilyfont{zhhei}{Noto Sans CJK SC}
\setCJKfamilyfont{zhkai}{LXGW WenKai}
\setCJKfamilyfont{zhbsong}{Noto Serif CJK SC Bold}
\newcommand*{\zhsong}{\CJKfamily{zhsong}}
\newcommand*{\zhhei}{\CJKfamily{zhhei}}
\newcommand*{\zhkai}{\CJKfamily{zhkai}}
\newcommand*{\zhbsong}{\CJKfamily{zhbsong}}
